nome = input('digite o seu nome: ')
print('Olá {}. Seja bem vindo!'.format(nome))
print(f'Olá {nome}. Seja bem vindo!')
print('Olá', nome, '. Seja bem vindo!')
print('Olá ' + nome + '. Seja bem Vindo!')
# print( 'desse modo eu percebom como posso printar a mesma mensagem utilizando 3 códigos diferentes')
