responsavel=input("Digite o nome do responsável: ")
funcionario=input("Digite o nome do funcionario: ")
evento=input('Digite o nome do evento: ')
valor=float(input("Digite o valor que será ressarcido: "))
print('Declaro para o senhor ' + responsavel+ ', que o senhor ' + funcionario + ' esteve presente no evento ' + evento + ', e gastou o valor de R$' + str(valor) + ' com a entrada.')
