nome=input("Digite um funcionário: ")
empresa=input("Digite a instituição: ")
qtde_funcionarios=int(input("digite a qtde de funcionários: "))
mediaMensalidade=float(input("digite a média de mensalidade: "))
print(nome + " trabalha na empresa " + empresa)
print("Possui:", qtde_funcionarios, "funcionarios.")
print("A média de mensalidade é de: "+ str(mediaMensalidade))
print("===========verifique os tipos de dados abaixo============")
print("O tipo de dado da variavel [nome] é: ",type(nome))
print("O tipo de dado da variavel [empresa] é:",type(empresa))
print("O tipo de dado da variavel [qtde de funcionarios] é: ",type(qtde_funcionarios))
print("O tipo de dado da variavel [mediaMensalidade] é: ",type(mediaMensalidade))
